apiVersion: config.istio.io/v1beta1
kind: DestinationPolicy
metadata:
  name: spring-boot-circuit-breaker-name-destination
  namespace: demo-istio
spec:
  destination:
    name: spring-boot-circuit-breaker-name
    labels:
      app: spring-boot-circuit-breaker-name
  circuitBreaker:
    simpleCb:
      sleepWindow: 1s
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 100
      httpConsecutiveErrors: 1